config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
# GET all cocktails routes and
# GET "cocktails/42/doses/new"

root to: 'cocktails#index'

resources :doses, only: [:destroy]
resources :cocktails

resources :cocktails do
  resources :doses, only: [:create, :new]
end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, presence: true, uniqueness: true
  mount_uploader :photo, PhotoUploader
end

# class Cocktail < ApplicationRecord
# end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates :cocktail, uniqueness: { scope: :ingredient,
     message: "You can only have one dose of each ingredient, chose another ingredient" }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_many :cocktails, through: :doses, dependent: :restrict_with_exception
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
before_action :set_cocktail, only: [:show]

  def index
    @cocktails = Cocktail.all
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.create(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo, :photo_cache)
  end

  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
before_action :set_dose, only: [:destroy]

  def create
    @dose = Dose.new(dose_params)
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose.cocktail = @cocktail
    @ingredients = Ingredient.all
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def new
    @dose = Dose.new
    @ingredients = Ingredient.all
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def destroy
    @cocktail = @dose.cocktail
    @dose.destroy
    redirect_to cocktail_path(@cocktail)
  end

private

  def dose_params
    params.require(:dose).permit(:name, :description, :cocktail_id, :ingredient_id)
  end

  def set_dose
    @dose = Dose.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/index.html.erb
<!-- Your banner code -->
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('http://mac.h-cdn.co/assets/16/15/980x490/landscape-1460656122-mcx-cocktails.jpg');">
  <div class="banner-content text-center">
    <h1>Cocktail Menu</h1>
    <p>Add your favourite cocktail to our database!</p>
 <!--    <a class="btn btn-primary btn-lg">Let's go...</a> -->
  </div>
</div>


<!-- PUT THE COCKTAILS IN CARDS: -->
<h1>Our Menu...</h1>
<BR>
  <%= link_to "Add a Cocktail", new_cocktail_url %>
<BR>
<div class="container">
  <div class="row">
    <% @cocktails.each do |cocktail|  %>
      <div class="col-md-4">
        <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path cocktail.photo if cocktail.photo.present? %>')">
          <h2 class="card-category"><%= cocktail.name.capitalize %></h2>
        </div>
      </div>
    <% end %>
  </div>
</div>

<BR><BR>
<!-- Your footer code -->
  <div class="footer text-center">
    <ul class="list-inline">
      <li>
        <a href="#"><i class="fa fa-facebook"></i></a>
      </li>

      <li>
        <a href="#"><i class="fa fa-youtube"></i></a>
      </li>

      <li>
        <a href="#"><i class="fa fa-linkedin"></i></a>
      </li>

      <li>
        <a href="#"><i class="fa fa-instagram"></i></a>
      </li>
    </ul>
    <p> This page was created during Le Wagon's first Tokyo Bootcamp, March 2017. Arigatou! </p>
  </div>

app/views/cocktails/new.html.erb
<h1>Add a Cocktail</h1>

<%= simple_form_for [@cocktail] do |f| %>
  <%= f.input :name %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
  <%= f.submit "Add a cocktail", class: "btn btn-primary" %>
<% end %>

<%= link_to "View all Cocktails", cocktails_path %>

app/views/cocktails/show.html.erb
<div>
<h2><%= @cocktail.name %></h2>
<% @cocktail.doses.each do |dose| %>
  <p><%= dose.description %>
  <%= dose.ingredient.name %></p>
  <% end %>
  <%= cl_image_tag @cocktail.photo, height: 250, width: 400, crop: :fill %>
</div>

<%= link_to "Add a dose", new_cocktail_dose_path(@cocktail) %>

<%= link_to "View all Cocktails", cocktails_path %>

app/views/doses/new.html.erb
<h1>Add a dose</h1>

<%= simple_form_for [@cocktail, @dose] do |f| %>
  <%= f.input :description %>
  <%= f.input :ingredient_id, as: :select, collection: @ingredients %>
  <%= f.submit "Add a dose", class: "btn btn-primary" %>
<% end %>

<%= link_to "View all Cocktails", cocktails_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
      <!-- Add these line for detecting device width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
  <%= render "shared/navbar_wagon_without_login" %>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar_wagon_without_login.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "cocktail_logo.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Search form -->
    <form action="" class="navbar-wagon-search">
      <input type="text" class="navbar-wagon-search-input" placeholder="Search something">
      <button type="submit" class="navbar-wagon-search-btn">
        <i class="fa fa-search"></i>
      </button>
    </form>

    <!-- Profile picture and dropdown -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <%= image_tag "http://unsplash.it/30x30", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <%= link_to "#" do %>
              <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
            <% end %>
          </li>
          <li>
            <%= link_to "#" do %>
              <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>

    <!-- Button (call-to-action) -->
    <%= link_to t(".top_call_to_action", default: "Add a cocktail"), new_cocktail_path, class: "navbar-wagon-item navbar-wagon-button btn" %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>